### ISSUE TITLE
move to python3

### ISSUE THREAD

**Issue by electron0zero** [raghavmittal101/moodle-fetch#1]
can we use python3 instead of python 2.7 ?

**Comment by raghavmittal101** [comment]
I am using `python-mechanize` which is not available for python3. We can later convert it to python3 by replacing `mechanize` with some other package.

**Comment by electron0zero** [comment]
look in this [script](https://github.com/electron0zero/BSER/blob/master/12thcomm/12thcomm.py)

**Comment by raghavmittal101** [comment]
I did `pip3 install mechanize` which installed successfully.
Then when I ran your script `python3 script.py` it gave following error
>python3 some_script.py 
Traceback (most recent call last):
  File "some_script.py", line 5, in <module>
    from mechanize import Browser
  File "/home/raghav/anaconda3/lib/python3.5/site-packages/mechanize/__init__.py", line 122, in <module>
    from _mechanize import \
ImportError: No module named '_mechanize'

**Comment by electron0zero** [comment]
@raghavmittal101 yeah i got the same error.
